### ISSUE TITLE
Labels missing when installed on Node js server

### ISSUE THREAD

**Issue by davout1806** [benwebber/tiddlywiki-dnd#14]
I have TW 5.1.23 running as Node js server (node v14.16.1) on Windows 10. Does this plugin work on node js? I'm trying to determine if the issue is with the plugin or my setup. 

If I install this plugin via drag, drop, import it seems to work fine (at least the spells).

If I install as detailed [here](https://tiddlywiki.com/#Installing%20a%20plugin%20from%20the%20plugin%20library) and [here](https://tiddlywiki.com/#Installing%20custom%20plugins%20on%20Node.js) by grabbing the code (all files and dirs under src dir) and placing it under npm\node_modules\tiddlywiki\plugins\benwebber\dnd\ and adding "benwebber/dnd" to list of plugins in tiddlywiki.info, the field labels are missing. Example below.

The only other plugins I have set for this sandbox wiki is below (although I do have other plugins in npm\node_modules\tiddlywiki\plugins for other wikis)
```
        "tiddlywiki/tiddlyweb",
        "tiddlywiki/filesystem",
        "tiddlywiki/highlight",
```
Thanks

![missing-labels](https://user-images.githubusercontent.com/5810136/126724260-151032d7-0a82-4a10-8ea5-39d992f95985.png)

**Comment by benwebber** [comment]
This is probably because the `src/` directory contains TypeScript, not JavaScript. You'll need the compiled sources. Admittedly, I haven't tested the plugin with the Node.js server yet.

Since you have Node.js installed, you can build the project like so:

1. Download an install [Yarn](https://yarnpkg.com/).
2. Build the plugin by running the following commands from the root of the repository:

    ```
    yarn install
    make
    ```

This will compile the TypeScript sources into JavaScript and output the entire plugin to the `build/` directory. You should be able to copy the `dnd` folder from there and install it to your wiki.

Let me know if this works, and I'll start attaching a tarball of the `build` directory to each release.

**Comment by davout1806** [comment]
Duh! Well that would explain it. I'll try to build this week and let you know. Thanks.

**Comment by davout1806** [comment]
That worked! Thanks so much.
